### ISSUE TITLE
Heroku precompile error

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5-project3#59]
Cant push to heroku to heroku

I am using the devise gem and it seems that if can't find variable current_user. Everything seems to be working on localhost...

```
remote:        I, [2015-05-13T17:46:57.240908 #1067]  INFO -- : Writing /tmp/build_a403f951e1ef0084a31689e9eeb04d1a/public/assets/application-6f7d4b846da10d82ad73a6202ac22695c16dc78ca4ca70975b4e18e72eca84a4.js
remote:        I, [2015-05-13T17:47:08.265546 #1067]  INFO -- : Writing /tmp/build_a403f951e1ef0084a31689e9eeb04d1a/public/assets/application-88360ee0240261147768bd38c4bac55ccf391ecfc6775124ebbaec4b0046fa52.css
remote:        rake aborted!
remote:        NameError: undefined local variable or method `current_user' for #<#<Class:0x007f765ecdb1e0>:0x007f76601e2138>
```

```
remote:        Tasks: TOP => assets:precompile
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
remote:
remote: Verifying deploy...
remote:
remote: !   Push rejected to giphy-stumble.
remote:
To https://git.heroku.com/giphy-stumble.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/giphy-stumble.git'
```

**Comment by RobertAKARobin** [comment]
Have you done `git add .` and `git commit` recently?

**Comment by presto2116** [comment]
right before setting up heroku

**Comment by RobertAKARobin** [comment]
That's strange. Well, it's saying that the last thing it tried to precompile is your application.css file. Copy and paste its contents into the CSS Validator to make sure it's OK. A missing semicolon caused Matt's Heroku build to crash.
http://jigsaw.w3.org/css-validator/#validate_by_input

**Comment by presto2116** [comment]
No errors in my css...

**Comment by RobertAKARobin** [comment]
What happens if you run `rake assets:precompile`?

**Comment by jrhorn424** [comment]
Also, have to ask... have you done a `heroku run rake db:migrate`? Can you get a line number and file from `heroku logs` to point us at where the error is coming from?

**Comment by presto2116** [comment]
the only place I am calling current_user is in my application.html.erb

```
<% if current_user %>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
      <li class="has-dropdown">
        <a href="#">Log in/Sign up</a>
        <ul class="dropdown">
         <li><a href="" data-reveal-id="sign-in-modal">Login</a></li>
         <li><a href="" data-reveal-id="sign-up-modal">Signup</a></li>
        </ul>
      </li>
      <% end %>
```

**Comment by presto2116** [comment]
rake assets:precompile fails as well

Jeff, I will try that

**Comment by presto2116** [comment]
```
14:24 giphy_stumble (master) $ heroku run rake db:migrate
Running `rake db:migrate` attached to terminal... up, run.1968
bash: rake: command not found
```

**Comment by RobertAKARobin** [comment]
It's not going to work until Heroku has been successfully deployed.

What message do you get when you run assets:precompile?

**Comment by presto2116** [comment]
```
14:33 giphy_stumble (master) $ rake assets:precompile
rake aborted!
NameError: undefined local variable or method `current_user' for #<#<Class:0x007fedb1c76220>:0x007fedb0436cf0>
/Users/pStraight/ga/projects/giphy_stumble/app/assets/stylesheets/backup.html.erb:4:in `_evaluate_template'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/erb_processor.rb:26:in `call'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/erb_processor.rb:13:in `call'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/loader.rb:45:in `block in load'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/loader.rb:156:in `fetch_asset_from_dependency_cache'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/loader.rb:38:in `load'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `yield'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/base.rb:63:in `find_asset'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/base.rb:70:in `find_all_linked_assets'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/manifest.rb:138:in `block in find'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/path_utils.rb:204:in `each'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:105:in `each'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:104:in `each'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/manifest.rb:136:in `find'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/sprockets/manifest.rb:162:in `compile'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-3.1.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/pStraight/.rvm/gems/ruby-2.2.0/gems/sprockets-rails-2.3.1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/pStraight/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/pStraight/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by jrhorn424** [comment]
Why is there an html/erb file in your assets pipeline? `/app/assets/stylesheets/backup.html.erb`

**Comment by presto2116** [comment]
I'm an idiot! misplaced that file

**Comment by presto2116** [comment]
works now! Thanks!
