### ISSUE TITLE
One of my gems made tests and they're breaking when I try to run my own

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#73]
I think one of my gems made tests, so when I run rspec they start to run, but break towards the end. My own tests are never run. 

Here's some of what appears in my terminal leading up to the error and the entire error:

```
(8.4ms)  CREATE TABLE "users" ("id" serial primary key, "email" character varying, "password" character varying, "password_digest" character varying, "remember_token" character varying, "username" character varying, "password_reset_token" character varying, "password_reset_sent_at" timestamp, "created_at" timestamp, "updated_at" timestamp)
   (3.3ms)  CREATE UNIQUE INDEX  "index_users_on_email" ON "users" USING btree ("email")
   (1.7ms)  CREATE  INDEX  "index_users_on_remember_token" ON "users" USING btree ("remember_token")
   (4.4ms)  CREATE TABLE "schema_migrations" ("version" character varying NOT NULL)
   (1.3ms)  CREATE UNIQUE INDEX  "unique_schema_migrations" ON "schema_migrations"  ("version")
   (0.4ms)  SELECT version FROM "schema_migrations"
   (1.2ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150513204557')
   (0.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150508175257')
   (0.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150508175321')
   (0.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150508194713')
   (0.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150508204638')
   (3.0ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150508210001')
   (2.1ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150513150740')
   (1.1ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150513204538')
   (0.4ms)  INSERT INTO "schema_migrations" (version) VALUES ('20150513204546')
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT "schema_migrations".* FROM "schema_migrations"
/Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- spec helper (LoadError)
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/lindsey/ga/project/comicbooklibrary/spec/controllers/users_controller_spec.rb:1:in `<top (required)>'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/bin/rspec:23:in `load'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/bin/rspec:23:in `<main>'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/lindsey/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mattscilipoti** [comment]
It looks like something is requiring `spec helper` instead of `spec_helper` (underscore instead of space).

**Comment by jshawl** [comment]
`require': cannot load such file -- spec helper (LoadError)`. I would recommend doing a full project search for `spec helper` with the space to locate the culprit!

**Comment by mattscilipoti** [comment]
Ping.  Is this resolved?
