### ISSUE TITLE
heroku problems

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5-project3#93]
I got it to deploy, but when I try and access the website it will not load

here is the link: http://giphy-stumble.herokuapp.com/

Looked at logs, but dont know what to make of them

**Comment by presto2116** [comment]
```
2015-05-15T14:19:51.526925+00:00 app[web.1]:     111:               <% @interests.order("interest ASC").each do |p| %>
2015-05-15T14:19:51.526934+00:00 app[web.1]:
2015-05-15T14:19:51.526928+00:00 app[web.1]:     114:                 <%=link_to p.interest.capitalize, interest_path(p.id), class:"a" %></li>
2015-05-15T14:19:51.526933+00:00 app[web.1]:
2015-05-15T14:19:51.526931+00:00 app[web.1]:   app/controllers/gifs_controller.rb:19:in `block (2 levels) in index'
2015-05-15T14:19:51.526918+00:00 app[web.1]: LINE 1: SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:19:51.526921+00:00 app[web.1]:     108:             </a>
2015-05-15T14:19:51.526924+00:00 app[web.1]:     110:               <li><a href="/" data-reveal-id="new-category-modal">New Category</a></li>
2015-05-15T14:19:51.526927+00:00 app[web.1]:     113:
2015-05-15T14:19:51.526932+00:00 app[web.1]:   app/controllers/gifs_controller.rb:18:in `index'
2015-05-15T14:19:51.524656+00:00 app[web.1]:   Interest Load (1.9ms)  SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:19:51.524666+00:00 app[web.1]: PG::UndefinedColumn: ERROR:  column "interest" does not exist
2015-05-15T14:19:51.524668+00:00 app[web.1]: LINE 1: SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:19:51.524669+00:00 app[web.1]:                                                         ^
2015-05-15T14:19:51.524670+00:00 app[web.1]: : SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:19:51.525446+00:00 app[web.1]: Completed 500 Internal Server Error in 807ms (ActiveRecord: 385.2ms)
2015-05-15T14:19:51.897710+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=giphy-stumble.herokuapp.com request_id=8f3b33fd-0b12-4bcc-be9d-a0da81d88a05 fwd="50.200.196.50" dyno=web.1 connect=1ms service=9ms status=304 bytes=133
2015-05-15T14:19:59.871994+00:00 app[web.1]: Started GET "/" for 50.200.196.50 at 2015-05-15 14:19:59 +0000
2015-05-15T14:19:59.874263+00:00 app[web.1]: Processing by GifsController#index as HTML
2015-05-15T14:20:00.257758+00:00 app[web.1]:   Rendered gifs/index.html.erb within layouts/application (0.1ms)
2015-05-15T14:20:00.263865+00:00 app[web.1]:   app/controllers/gifs_controller.rb:18:in `index'
2015-05-15T14:20:00.263842+00:00 app[web.1]:
2015-05-15T14:20:00.263844+00:00 app[web.1]: ActionView::Template::Error (PG::UndefinedColumn: ERROR:  column "interest" does not exist
2015-05-15T14:20:00.263847+00:00 app[web.1]:                                                         ^
2015-05-15T14:20:00.263849+00:00 app[web.1]:     108:             </a>
2015-05-15T14:20:00.263845+00:00 app[web.1]: LINE 1: SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:20:00.263848+00:00 app[web.1]: : SELECT "interests".* FROM "interests"  ORDER BY interest ASC):
2015-05-15T14:20:00.263850+00:00 app[web.1]:     109:             <ul class="dropdown" style="overflow-y:scroll;height:400px !important">
2015-05-15T14:20:00.263863+00:00 app[web.1]:   app/views/layouts/application.html.erb:111:in `_app_views_layouts_application_html_erb__2839074840579898655_69868839978740'
2015-05-15T14:20:00.263852+00:00 app[web.1]:     110:               <li><a href="/" data-reveal-id="new-category-modal">New Category</a></li>
2015-05-15T14:20:00.263854+00:00 app[web.1]:     112:               <li>
2015-05-15T14:20:00.263853+00:00 app[web.1]:     111:               <% @interests.order("interest ASC").each do |p| %>
2015-05-15T14:20:00.263855+00:00 app[web.1]:     113:
2015-05-15T14:20:00.263861+00:00 app[web.1]:     114:                 <%=link_to p.interest.capitalize, interest_path(p.id), class:"a" %></li>
2015-05-15T14:20:00.263864+00:00 app[web.1]:   app/controllers/gifs_controller.rb:19:in `block (2 levels) in index'
2015-05-15T14:20:00.263866+00:00 app[web.1]:
2015-05-15T14:20:00.263868+00:00 app[web.1]:
2015-05-15T14:20:00.261585+00:00 app[web.1]: LINE 1: SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:20:00.261574+00:00 app[web.1]:   Interest Load (1.6ms)  SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:20:00.261583+00:00 app[web.1]: PG::UndefinedColumn: ERROR:  column "interest" does not exist
2015-05-15T14:20:00.261587+00:00 app[web.1]: : SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:20:00.262399+00:00 app[web.1]: Completed 500 Internal Server Error in 388ms (ActiveRecord: 1.6ms)
2015-05-15T14:20:00.261586+00:00 app[web.1]:                                                         ^
2015-05-15T14:20:00.271068+00:00 heroku[router]: at=info method=GET path="/" host=giphy-stumble.herokuapp.com request_id=3ac562a9-c525-4fdf-990c-5858e9dd7510 fwd="50.200.196.50" dyno=web.1 connect=2ms service=401ms status=500 bytes=1754
2015-05-15T14:21:22.399770+00:00 heroku[api]: Starting process with command `bundle exec rake db:setup` by preston.straight@gmail.com
2015-05-15T14:21:27.451639+00:00 heroku[run.6011]: Awaiting client
2015-05-15T14:21:27.512462+00:00 heroku[run.6011]: Starting process with command `bundle exec rake db:setup`
2015-05-15T14:21:27.680008+00:00 heroku[run.6011]: State changed from starting to up
2015-05-15T14:21:48.973605+00:00 heroku[run.6011]: State changed from up to complete
2015-05-15T14:21:48.960433+00:00 heroku[run.6011]: Process exited with status 0
2015-05-15T14:21:53.643280+00:00 app[web.1]: Started GET "/" for 50.200.196.50 at 2015-05-15 14:21:53 +0000
2015-05-15T14:21:53.746430+00:00 app[web.1]: Processing by GifsController#index as HTML
2015-05-15T14:21:54.367374+00:00 heroku[router]: at=info method=GET path="/" host=giphy-stumble.herokuapp.com request_id=aec2117d-d7d3-4351-8c4e-c22c668cacb1 fwd="50.200.196.50" dyno=web.1 connect=1ms service=726ms status=500 bytes=1754
2015-05-15T14:21:54.208700+00:00 app[web.1]:   Rendered gifs/index.html.erb within layouts/application (0.1ms)
2015-05-15T14:21:54.355471+00:00 app[web.1]:   Rendered login_forms/_sign_in.html.erb (36.3ms)
2015-05-15T14:21:54.361882+00:00 app[web.1]:   Rendered interests/_new.html.erb (2.2ms)
2015-05-15T14:21:54.363770+00:00 app[web.1]:
2015-05-15T14:21:54.363772+00:00 app[web.1]: ActionView::Template::Error (undefined method `interest' for #<Interest id: nil, user_id: nil, interests: nil>):
2015-05-15T14:21:54.363774+00:00 app[web.1]:     3: <%= form_for @interest do |f| %>
2015-05-15T14:21:54.363775+00:00 app[web.1]:     4:
2015-05-15T14:21:54.363776+00:00 app[web.1]:     5:
2015-05-15T14:21:54.363777+00:00 app[web.1]:     6: <%= f.text_field :interest, :placeholder => "New Category", class:"left inline"  %></p>
2015-05-15T14:21:54.363778+00:00 app[web.1]:     7:
2015-05-15T14:21:54.363780+00:00 app[web.1]:     8: <p><%= f.submit "Stumble", :class => "button", :id => "interest-stumble" %></p>
2015-05-15T14:21:54.363781+00:00 app[web.1]:     9: <% end %>
2015-05-15T14:21:54.363782+00:00 app[web.1]:   app/views/interests/_new.html.erb:6:in `block in _app_views_interests__new_html_erb__2327910367905509968_69868840394540'
2015-05-15T14:21:54.363783+00:00 app[web.1]:   app/views/interests/_new.html.erb:3:in `_app_views_interests__new_html_erb__2327910367905509968_69868840394540'
2015-05-15T14:21:54.363785+00:00 app[web.1]:   app/views/layouts/application.html.erb:139:in `_app_views_layouts_application_html_erb__2839074840579898655_69868839978740'
2015-05-15T14:21:54.363786+00:00 app[web.1]:   app/controllers/gifs_controller.rb:19:in `block (2 levels) in index'
2015-05-15T14:21:54.363790+00:00 app[web.1]:
2015-05-15T14:21:54.363788+00:00 app[web.1]:   app/controllers/gifs_controller.rb:18:in `index'
2015-05-15T14:21:54.363789+00:00 app[web.1]:
2015-05-15T14:21:54.318113+00:00 app[web.1]:   Interest Load (107.5ms)  SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:21:54.358982+00:00 app[web.1]:   Rendered login_forms/_sign_up.html.erb (2.7ms)
2015-05-15T14:21:54.362088+00:00 app[web.1]: Completed 500 Internal Server Error in 616ms (ActiveRecord: 117.7ms)
2015-05-15T14:21:54.710616+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=giphy-stumble.herokuapp.com request_id=ace7de1d-2579-4d72-a7ac-1ae78c2e7989 fwd="50.200.196.50" dyno=web.1 connect=1ms service=5ms status=304 bytes=133
2015-05-15T14:22:04.323385+00:00 app[web.1]: Started GET "/" for 50.200.196.50 at 2015-05-15 14:22:04 +0000
2015-05-15T14:22:04.326331+00:00 app[web.1]: Processing by GifsController#index as HTML
2015-05-15T14:22:04.775391+00:00 app[web.1]:   Rendered gifs/index.html.erb within layouts/application (0.1ms)
2015-05-15T14:22:04.781298+00:00 app[web.1]:   Rendered login_forms/_sign_in.html.erb (2.4ms)
2015-05-15T14:22:04.787935+00:00 app[web.1]:
2015-05-15T14:22:04.787938+00:00 app[web.1]: ActionView::Template::Error (undefined method `interest' for #<Interest id: nil, user_id: nil, interests: nil>):
2015-05-15T14:22:04.785913+00:00 app[web.1]:   Rendered interests/_new.html.erb (1.1ms)
2015-05-15T14:22:04.787940+00:00 app[web.1]:     3: <%= form_for @interest do |f| %>
2015-05-15T14:22:04.787943+00:00 app[web.1]:     6: <%= f.text_field :interest, :placeholder => "New Category", class:"left inline"  %></p>
2015-05-15T14:22:04.787945+00:00 app[web.1]:     8: <p><%= f.submit "Stumble", :class => "button", :id => "interest-stumble" %></p>
2015-05-15T14:22:04.787941+00:00 app[web.1]:     4:
2015-05-15T14:22:04.787942+00:00 app[web.1]:     5:
2015-05-15T14:22:04.787944+00:00 app[web.1]:     7:
2015-05-15T14:22:04.787948+00:00 app[web.1]:   app/views/interests/_new.html.erb:6:in `block in _app_views_interests__new_html_erb__2327910367905509968_69868840394540'
2015-05-15T14:22:04.787947+00:00 app[web.1]:     9: <% end %>
2015-05-15T14:22:04.787949+00:00 app[web.1]:   app/views/interests/_new.html.erb:3:in `_app_views_interests__new_html_erb__2327910367905509968_69868840394540'
2015-05-15T14:22:04.787952+00:00 app[web.1]:   app/controllers/gifs_controller.rb:19:in `block (2 levels) in index'
2015-05-15T14:22:04.787950+00:00 app[web.1]:   app/views/layouts/application.html.erb:139:in `_app_views_layouts_application_html_erb__2839074840579898655_69868839978740'
2015-05-15T14:22:04.787953+00:00 app[web.1]:   app/controllers/gifs_controller.rb:18:in `index'
2015-05-15T14:22:04.787954+00:00 app[web.1]:
2015-05-15T14:22:04.787955+00:00 app[web.1]:
2015-05-15T14:22:04.778469+00:00 app[web.1]:   Interest Load (1.1ms)  SELECT "interests".* FROM "interests"  ORDER BY interest ASC
2015-05-15T14:22:04.783702+00:00 app[web.1]:   Rendered login_forms/_sign_up.html.erb (1.5ms)
2015-05-15T14:22:04.786297+00:00 app[web.1]: Completed 500 Internal Server Error in 460ms (ActiveRecord: 1.1ms)
2015-05-15T14:22:04.789893+00:00 heroku[router]: at=info method=GET path="/" host=giphy-stumble.herokuapp.com request_id=548f3f44-14c7-4f90-a7e3-88d588c29860 fwd="50.200.196.50" dyno=web.1 connect=1ms service=469ms status=500 bytes=1754
```

**Comment by mattscilipoti** [comment]
After formatting it, via three back-ticks, I see the errors: `PG::UndefinedColumn: ERROR:  column "interest" does not exist` and `undefined method 'interest'`

**Comment by andrewsunglaekim** [comment]
pro tip: you can change your environment on your heroku app to development so you can read error messages by doing this:

`heroku config:set RAILS_ENV=development` in the root directory of your application

**Comment by presto2116** [comment]
got it to work
